### ISSUE TITLE
Google image search API is broken

### ISSUE THREAD

**Issue by amol9** [amol9/wallp#3]
PS C:\Windows\system32> wallp change -s google -q "blue"
[google] . Traceback (most recent call last):
  File "C:\Python34\Scripts\wallp-script.py", line 9, in <module>
    load_entry_point('wallp==1.9.0', 'console_scripts', 'wallp')()
  File "C:\Python34\lib\site-packages\wallp\client\main.py", line 21, in main
    command.execute()
  File "C:\Python34\lib\site-packages\wallp\command\command.py", line 34, in execute
    subcmd_func.execute(args)
  File "C:\Python34\lib\site-packages\wallp\command\subcommand.py", line 21, in execute
    self.func(self.subcmd, *arg_list)
  File "C:\Python34\lib\site-packages\wallp\command\subcommands\change_subcommand.py", line 21, in change
    client.change_wallpaper()
  File "C:\Python34\lib\site-packages\wallp\client\client.py", line 54, in change_wallpaper
    filepath, im_width, im_height, image_id = self.get_image()
  File "C:\Python34\lib\site-packages\wallp\client\client.py", line 106, in get_image
    temp_image_path, ext, image_url = self.get_image_to_temp_file(service, self._query, self._color)
  File "C:\Python34\lib\site-packages\wallp\client\client.py", line 154, in get_image_to_temp_file
    image_url = service.get_image_url(query=query, color=color)
  File "C:\Python34\lib\site-packages\wallp\service\google.py", line 39, in get_image_url
    self.search(query, color)
  File "C:\Python34\lib\site-packages\wallp\service\google.py", line 72, in search
    results = jdata['responseData']['results']
TypeError: 'NoneType' object is not subscriptable

**Comment by amol9** [comment]
Fixed (commit: https://github.com/amol9/wallp/commit/ed7894b45c6c28eee25110ca228437882134c215).
