### ISSUE TITLE
Crash when I run wallp

### ISSUE THREAD

**Issue by musale** [amol9/wallp#4]
I'm getting this error when I run `wallp`

`source : imgur`
`Traceback (most recent call last):
  File "/usr/bin/wallp", line 9, in <module>
    load_entry_point('wallp==2.0.27', 'console_scripts', 'wallp')()
  File "/usr/lib/python2.7/site-packages/wallp/main.py", line 34, in main
    default_subcommand='source random', moves=True, update_autocomplete_cb=update_autocomplete_cb)
  File "/usr/lib/python2.7/site-packages/redcmd/func.py", line 47, in execute_commandline
    cl.execute()
  File "/usr/lib/python2.7/site-packages/redcmd/commandline.py", line 79, in execute
    self._command_collection.execute(args, namespace)
  File "/usr/lib/python2.7/site-packages/redcmd/command_collection.py", line 510, in execute
    return cmd_func.execute(args)
  File "/usr/lib/python2.7/site-packages/redcmd/cmdfunc.py", line 25, in execute
    return self.func(*self.get_arg_list(self.func, args))
  File "/usr/lib/python2.7/site-packages/wallp/subcmd/source/random.py", line 18, in random
    self.change_wallpaper(sp)
  File "/usr/lib/python2.7/site-packages/wallp/subcmd/source/base.py", line 52, in change_wallpaper
    wallpaper.change()
  File "/usr/lib/python2.7/site-packages/wallp/wallpaper.py", line 48, in change
    source, image = self.get_image()
  File "/usr/lib/python2.7/site-packages/wallp/wallpaper.py", line 113, in get_image
    image = source.get_image(params=params)
  File "/usr/lib/python2.7/site-packages/wallp/source/imgur.py", line 71, in get_image
    self._images = Images(self._params, cache=True, cache_timeout='1h', trace=self._trace, cache_load=cache_load)
  File "/usr/lib/python2.7/site-packages/wallp/source/images.py", line 25, in __init__
    self._filter    = ImageFilter()
  File "/usr/lib/python2.7/site-packages/wallp/source/image_filter.py", line 16, in __init__
    dw, dh = dt.get_size()
AttributeError: 'NoneType' object has no attribute 'get_size'
`

**Comment by amol9** [comment]
Currently, it supports Windows and Linux (GNOME / KDE). If you are using any other OS or desktop manager, you'll get this kind of error.

**Comment by musale** [comment]
Ohh cool. I use i3 Window Manager ... Maybe I could PR for it sometime?

**Comment by amol9** [comment]
sure. good starting point will be "desktop" dir in sources, esp. the function: get_desktop().

**Comment by amol9** [comment]
Fixed in commit: https://github.com/amol9/wallp/commit/13bbc87743f19107efa132ff929359e83e5bc71b
